exammanagement/exammanagement/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import include, path
from django.views.generic import RedirectView
from main import views
from main.customreverse import customreverse_lazy as reverse

urlpatterns = [
    path("admin/", admin.site.urls),
    path("0/admin/", admin.site.urls),
    path("", RedirectView.as_view(url="main/")),
    path("main/", include("main.urls")),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("logout", views.logout_request, name="logout"),
    path("activate/<uidb64>/<token>", views.activate_account, name="activate"),
    path("i18n/", include("django.conf.urls.i18n")),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            html_email_template_name="registration/password_reset_email.html",
            email_template_name="registration/password_reset_email.html",
            success_url=reverse("password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += i18n_patterns(
    path("main/", include("main.urls")),
    path("register", views.register_request, name="register"),
    path("login", views.login_request, name="login"),
    path("activate/<uidb64>/<token>", views.activate_account, name="activate"),
    path(
        "password_reset/",
        auth_views.PasswordResetView.as_view(
            template_name="registration/password_reset_form.html",
            html_email_template_name="registration/password_reset_email.html",
            email_template_name="registration/password_reset_email.html",
            success_url=reverse("password_reset_done"),
        ),
        name="password_reset",
    ),
    path(
        "password_reset/done/",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "reset/<uidb64>/<token>/",
        auth_views.PasswordResetConfirmView.as_view(
            success_url=reverse("password_reset_complete"),
        ),
        name="password_reset_confirm",
    ),
    path(
        "reset/done/",
        auth_views.PasswordResetCompleteView.as_view(),
        name="password_reset_complete",
    ),
)

exammanagement/main/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path("", views.SubjectListView.as_view(), name="index"),
    path("subjects/", views.SubjectListView.as_view(), name="subjects"),
    path(
        "subjects/enrolled/",
        views.EnrolledSubjectListView.as_view(),
        name="enrolled-subjects",
    ),
    path("subject/<int:pk>", views.SubjectDetailView.as_view(), name="subject-detail"),
    path("chapter/<int:pk>", views.ChapterDetailView.as_view(), name="chapter-detail"),
    path(
        "subject/<int:subject_id>/enroll/",
        views.enroll_subject,
        name="subject-registration",
    ),
    path("profile/<int:pk>", views.user_profile, name="user-profile"),
    path("create-exam/chapter/<int:pk>", views.create_exam_view, name="create-exam"),
    path("exam/<int:pk>", views.take_exam_view, name="take-exam"),
    path("edit-profile", views.edit_profile, name="edit-profile"),
    path("mark-read", views.mark_notification_as_read, name="mark-read"),
    path(
        "get-image-upload-url", views.get_image_upload_url, name="get-image-upload-url"
    ),
]

exammanagement/main/models.py
import uuid

from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.db import models
from django.utils.translation import gettext_lazy as _
from pyexcel_xlsx import get_data

from .customreverse import customreverse as reverse

# Create your models here.


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    introduction = models.TextField(max_length=1000, blank=True, null=True)
    date_of_birth = models.DateField(
        help_text=_("Date of Birth of user"), blank=True, null=True
    )
    avatar = models.URLField(blank=True, null=True, max_length=1000)

    def get_absolute_url(self):
        return reverse("user-profile", args=[str(self.id)])


class Genre(models.Model):
    name = models.CharField(
        max_length=200, help_text=_("Genre of the subject (IT, Japanese, etc)")
    )

    def __str__(self):
        return self.name


class Subject(models.Model):
    name = models.CharField(max_length=200, help_text=_("Title name of the subject"))
    description = models.TextField(
        max_length=1000, help_text=_("Description"), blank=True
    )
    genres = models.ManyToManyField(Genre, help_text=_("Select genre for this subject"))
    enrollers = models.ManyToManyField(User, through="Enroll")

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("subject-detail", args=[str(self.id)])

    def display_genre(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ", ".join(genre.name for genre in self.genres.all())

    display_genre.short_description = "Genre"


class Chapter(models.Model):
    name = models.CharField(max_length=200, help_text=_("Title name of the chapter"))
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    min_correct_ans = models.PositiveIntegerField(
        help_text=_("Minimum correct answers to pass the test")
    )
    time_limit = models.PositiveIntegerField(help_text=_("Time limit for the test"))
    num_questions = models.PositiveIntegerField(default=20)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("chapter-detail", args=[str(self.id)])

    def clean(self):
        if self.min_correct_ans > self.num_questions:
            raise ValidationError(
                _("Minimum correct answers must be less than number of questions")
            )


class Enroll(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    subject = models.ForeignKey(Subject, on_delete=models.CASCADE)
    progress = models.PositiveIntegerField(default=0)
    SUBJECT_STATUS = (
        (1, "Completed"),
        (0, "Incomplete"),
    )
    status = models.IntegerField(
        choices=SUBJECT_STATUS,
        blank=True,
        default=0,
    )

    class Meta:
        unique_together = ("user", "subject")


class Test(models.Model):
    user = models.ForeignKey(User, on_delete=models.PROTECT)
    chapter = models.ForeignKey(Chapter, on_delete=models.PROTECT)
    total_score = models.IntegerField()
    created_at = models.DateTimeField()
    completed_at = models.DateTimeField(null=True, blank=True)
    TEST_STATUS = (
        (1, "Completed"),
        (0, "Incomplete"),
    )
    status = models.IntegerField(
        choices=TEST_STATUS,
        blank=True,
        default=0,
    )

    @property
    def passed(self):
        return self.total_score >= self.chapter.min_correct_ans

    @property
    def num_questions(self):
        return Choice.objects.filter(
            test=self,
        ).count()

    @property
    def time(self):
        if self.completed_at is None:
            return _("Not completed yet")
        time = self.completed_at - self.created_at

        if time.seconds < 60:
            return _("%d seconds") % time.seconds
        elif time.seconds < 3600:
            return _("%d minutes") % (time.seconds // 60)
        else:
            return _("%d hours") % (time.seconds // 3600) + _("%d minutes") % (
                (time.seconds % 3600) // 60
            )

    def get_absolute_url(self):
        return reverse("take-exam", args=[str(self.id)])

    def calculate_total_score(self):
        choices = Choice.objects.filter(test=self)
        total_score = 0
        for choice in choices:
            if choice.answer and choice.answer.is_correct:
                total_score += 1
        return total_score


class Question(models.Model):
    id = models.CharField(
        primary_key=True, max_length=100, default=uuid.uuid4, editable=False
    )
    description = models.TextField(
        max_length=1000, help_text=_("Detail of the question")
    )
    chapter = models.ForeignKey(Chapter, on_delete=models.CASCADE)


class Answer(models.Model):
    content = models.TextField(max_length=1000, help_text=_("Content of the answer"))
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    is_correct = models.BooleanField(default=False)


class Choice(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    test = models.ForeignKey(Test, on_delete=models.CASCADE)
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    answer = models.ForeignKey(Answer, on_delete=models.CASCADE, null=True)


class Notification(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content = models.TextField(
        max_length=1000, help_text=_("Content of the notification")
    )
    url = models.CharField(
        max_length=1000, help_text=_("URL of the notification"), null=True
    )
    updated_chapter = models.ForeignKey(
        Chapter, on_delete=models.CASCADE, null=True, blank=True
    )
    created_at = models.DateTimeField(auto_now_add=True)
    is_read = models.BooleanField(default=False)


class QuestionSetImport(models.Model):
    id = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=512)
    filename = models.FileField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def clean(self):
        try:
            data = get_data(self.filename.file)
        except Exception as e:
            raise ValidationError(str(e))

        # The data will be in the following format
        # Column A: Subject
        # Column B: Chapter
        # Column C: Question ID
        # Column D: Question Description
        # Column E: Correct Answers (separated by comma) (ex: 1,2,3)
        # Column F onwards: Answers

        for row in data["Sheet1"]:
            if len(row) < 5:
                raise ValidationError(_("Not enough columns"))

            (
                subject_name,
                chapter_name,
                question_id,
                question_description,
                correct_answers,
            ) = row[:5]

            if (
                subject_name == ""
                or chapter_name == ""
                or question_id == ""
                or question_description == ""
                or correct_answers == ""
            ):
                raise ValidationError(_("All fields are required"))

            question = Question.objects.filter(id=question_id).first()
            if question is not None:
                raise ValidationError(_("Question ID already exists"))

            try:
                correct_answers = [
                    int(float(x)) for x in str(correct_answers).split(",")
                ]
            except Exception as e:
                raise ValidationError(
                    _("Correct answers must be a list of numbers separated by comma")
                )

            for index, answer in enumerate(row[5:]):
                if answer == "":
                    raise ValidationError(_("All answers are required"))

    def save(self, *args, **kwargs):
        data = get_data(self.filename.file)

        for row in data["Sheet1"]:
            (
                subject_name,
                chapter_name,
                question_id,
                question_description,
                correct_answers,
            ) = row[:5]

            subject = Subject.objects.filter(name=subject_name).first()
            if subject is None:
                subject = Subject(name=subject_name)
                subject.save()

            chapter = Chapter.objects.filter(
                name=chapter_name,
                subject=subject,
            ).first()

            if chapter is None:
                chapter = Chapter(
                    name=chapter_name,
                    subject=subject,
                    num_questions=0,
                    min_correct_ans=0,
                    time_limit=0,
                )
                chapter.save()

            question = Question(
                id=question_id, description=question_description, chapter=chapter
            )
            question.save()

            correct_answers = [int(float(x)) for x in str(correct_answers).split(",")]

            for index, answer in enumerate(row[5:]):
                answer = Answer(
                    content=answer,
                    question=question,
                    is_correct=((index + 1) in correct_answers),
                )
                answer.save()

        self.filename = None

        super(QuestionSetImport, self).save(*args, **kwargs)

exammanagement/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

from .models import Profile

# Create your forms here.


class NewUserForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ("username", "email", "password1", "password2")

    def save(self, commit=True):
        user = super(NewUserForm, self).save(commit=False)
        user.email = self.cleaned_data["email"]
        user.is_active = False
        if commit:
            user.save()
            Profile.objects.create(user=user)
        return user


class EditProfileForm(forms.ModelForm):
    date_of_birth = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )

    class Meta:
        model = Profile
        exclude = ("user",)

exammanagement/main/templates/main/chapter_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load keyvalue_action %}
{% block content %}
    <div class="container mt-5">
        <div class="card text-center">
            <h5 class="card-header">
                {{ chapter.name }} - {{ chapter.subject.name}}
            </h5>
            <div class="card-body">
                <p class="card-text">{% trans "Total questions" %}: {{ chapter.num_questions }}</p>
                <p class="card-text">{% trans "Time limit" %}: {{ chapter.time_limit }} {% trans "minutes" %}</p>
                <p class="card-text">{% trans "Minium correct answers" %}: {{ chapter.min_correct_ans }}</p>
                <form action="{% customurl 'create-exam' chapter.id %}" method="post">
                    {% csrf_token %}
                    <button class="btn btn-primary" type="submit">{% trans "Do test" %}</button>
                  </form>
            </div>
        </div>
    </div>

    <div class="mt-5">
        <h3>{% trans "Exam History" %}</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>{% trans "Date" %}</th>
                    <th>{% trans "Score" %}</th>
                    <th>{% trans "Finished Time" %}</th>
                    <th>{% trans "Passed" %}</th>
                    <th>{% trans "Details" %}</th>
                </tr>
            </thead>
            <tbody>
                {% for test in tests %}
                    <tr>
                        <td>{{ test.created_at }}</td>
                        <td>{{ test.total_score }} / {{ test.num_questions }}</td>
                        <td>{{ test.time }}</td>
                        <td>
                            {% if test.passed %}
                                Passed
                            {% else %}
                                Failed
                            {% endif %}
                        </td>
                        <td>
                            <a href="{{ test.get_absolute_url }}">
                                {% trans "View Details" %}
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="2">{% trans "No exam history available." %}</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

exammanagement/main/templates/main/edit_profile.html
{% extends "base_generic.html"%}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% load bootstrap5 %}
{% load widget_tweaks %}
{% load keyvalue_action %}

{% block content %}
<div class="container">
    <form
        id="profile-form"
        method="POST"
        enctype="multipart/form-data"
        data-post-url="{% customurl 'get-image-upload-url' %}"
    >
        {% csrf_token %}
        <input type="hidden" name="_method" value="PATCH">
        <div class="row">
            <div class="col-8 offset-2">
                <div class="row fw-bold fs-3">{% trans "Edit Profile" %}</div>
                    {{ form|crispy }}
                    <img
                        id="preview"
                        width="200"
                        style="display:block;"
                        src="{{ user.profile.avatar }}"
                        onerror="this.src='{% static 'image/avatar.png' %}'"
                    />
                <div class="row pt-3">
                    <button class="btn btn-primary" type="submit">{% trans "Save Changes" %}</button>
                </div>
            </div>
        </div>
    </form>
</div>
<style>
    #id_avatar {
        display: none;
    }
</style>
{% endblock %}

exammanagement/main/templates/main/subject_detail.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load keyvalue_action %}

{% block content %}
    {% load static %}
    <section class="img-fluid pb-4 subject-bg">
        <div class="container">
            <p class="display-2 fw-bold pt-4">{{subject.name }}</p>
            <p class="fs-4 pt-2">{{subject.description }}</p>
            {% if user.is_authenticated %}
                <div class="d-flex">
                    <div class="align-self-center ms-3">
                        {% if is_enrolled %}
                            <button class="btn btn-primary" disabled>{% trans "Enrolled" %}</button>
                        {% else %}
                            <form method="post" id="registration-form" data-registration-url="{% customurl 'subject-registration' subject.id %}">
                                {% csrf_token %}
                                <button class="btn btn-primary" id="enroll-button" type="submit">{% trans "Register" %}</button>
                            </form>
                        {% endif %}
                    </div>
                    <div class="align-self-center ms-3">
                        <span><i class="fa fa-user" aria-hidden="true"></i></span>
                        <span id="enrolling">{{ enrollercount }}</span>
                    </div>
                    <div class="align-self-center ms-3" id="registration-status"></div>
                </div>
            {% endif %}
        </div>
    </section>
    <section>
        <div class="container mt-3">
            <ul class="nav nav-tabs" id="myTabs">
                <li class="nav-item">
                    <a class="nav-link active" data-toggle="tab" href="#tab1">{% trans "Chapters list" %}</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="tab" href="#tab2">{% trans "Leaderboard" %}</a>
                </li>
                <!-- Add more tabs as needed -->
            </ul>

            <div class="tab-content">
                <div class="tab-pane fade show active" id="tab1">
                    <!-- Content for Tab 1 -->
                    <p class="fs-3 fw-bold">{% trans "Chapters list" %}</p>
                    <div class="card" >
                        <div class="card-header w-full">
                            {{ subject.name }}
                        </div>
                        <ul id="chapters-list" class="list-group list-group-flush">
                            {% for chapter in chapters %}
                                <li id="lesson-{{ chapter.id }}" class="list-group-item">
                                    <div class="d-flex justify-content-between">
                                        <span class="mr-3 fw-bold align-self-center">
                                            <a href="{{ chapter.get_absolute_url }}">{{ chapter.name }}</a>
                                            {% if chapter.test_set|in_category:user|in_contain_more:chapter.min_correct_ans %}
                                                <i class="fa-solid fa-check text-success ms-2"></i>
                                            {% endif %}
                                        </span>
                                        {% if user.is_superuser %}
                                        <div>
                                            <button type="button" class="btn btn-danger me-1">{% trans "Delete"%}</button>
                                            <button type="button" class="btn btn-primary">{% trans "Update"%}</button>
                                        </div>
                                        {% elif user.is_authenticated %}
                                            <a href="{{ chapter.get_absolute_url }}"><button type="button" class="btn btn-primary">{% trans "Detail"%}</button></a>
                                        {% endif %}
                                    </div>
                                </li>
                            {% empty %}
                                <h5>{% trans "There are no chapters in this subject" %}</h5>
                            {% endfor %}
                        </ul>
                    </div>
                    {% if user.is_superuser %}
                        <div class="card mt-5 mb-3 w-half">
                            <button type="button" class="btn btn-primary">{% trans "Add chapter" %}</button>
                        </div>
                    {% endif %}
                </div>
                <div class="tab-pane fade" id="tab2">
                    <!-- Content for Tab 2 -->
                    <p class="fs-3 fw-bold">{% trans "Leaderboard" %}</p>
                    <div class="card" >
                        <div class="card-header w-full">
                            {{ subject.name }}
                        </div>
                        <table id="enrollTable" class="table table-striped">
                            <thead>
                                <tr>
                                    <th>{% trans "Username" %}</th>
                                    <th>{% trans "Progress" %}</th>
                                    <th>{% trans "Total scored" %}</th>
                                    <th>{% trans "Times" %}</th>
                                    <th>{% trans "Correct ratio" %}</th>
                                </tr>
                            </thead>
                            <tbody>
                                {% for enroller in enrollers %}
                                    <tr>
                                        <td class="fw-bold"><a href="{{ enroller.user.profile.get_absolute_url }}">{{ enroller.user.username }}</a></td>
                                        <td>{{ enroller.subject|in_progress:enroller.user }}%</td>
                                        <td>{{enroller|total_correct_cal:enroller.subject}}</td>
                                        <td>{{enroller|total_times:enroller.subject}}</td>
                                        <td>{{enroller|correct_ratio:enroller.subject}}%</td>
                                    </tr>
                                {% empty %}
                                    <h6>{% trans "There are no user enrolled this subject" %}</h6>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

exammanagement/main/templates/main/take_exam.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load keyvalue_action %}

{% block content %}
    <div class="p-4 shadow-4 rounded-3 my-4 exam-bg">
        <form class="form" id="exam-form" method="POST">
            {% csrf_token %}
            <h2 class="text-center">{% trans "Chapter" %}: {{ test.chapter.name }} - {{ test.chapter.subject.name }}</h2>
            <h2 class="text-center" id="countdown" data-remaining-seconds="{{ remaining_time_seconds }}"></h2>
            {% for c in choices %}
                <div class="d-flex w-100 align-items-center">
                    <div class="col-auto flex-shrink-1 flex-grow-1">
                        <h5 class="">{{ forloop.counter }}. {{c.question.description}}</h5>
                    </div>
                </div>
                {% for answer in c.question.answer_set.all %}
                    <div class="form-check mx-4 d-flex align-items-center">
                        {% if user_response %}
                        <input class="form-check-input"
                            type="radio"
                            name="question_{{ c.question.id }}"
                            value="{{ answer.id }}" {% if user_response|keyvalue:c.question.id == answer.id %} checked {% endif %}>
                        {% else %}
                            <input class="form-check-input"
                                type="radio"
                                name="question_{{ c.question.id }}"
                                value="{{ answer.id }}"
                            >
                        {% endif %}
                        <label class="form-check-label ml-3" for="{{ answer.id }}">
                            {{answer.content}}
                        </label>
                    </div>
                {% endfor %}
            {% endfor %}
            <input class="btn btn-primary btn-lg" style="border-radius: 0%;" type="submit" value="Submit Answers">
        </form>
    </div>
{% endblock %}

exammanagement/main/templates/main/test-results.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load keyvalue_action %}

{% block content %}
    <div class="p-4 shadow-4 rounded-3 my-4 exam-bg">
        <h2 class="text-center">{% trans "Chapter" %}: {{ test.chapter.name }} - {{ test.chapter.subject.name }}</h2>
        <h2 class="{% if test.total_score >= test.chapter.min_correct_ans %} text-success {% else %} text-danger {% endif %} text-center">
            {% trans "Total score" %}: {{ test.total_score }} / {{ test.choice_set.all.count }}
        </h2>
        <h4 class="text-secondary fs-6">{% trans "Created at" %}: {{ test.created_at }}</h4>
        <h4 class="text-secondary fs-6">{% trans "Completed at" %}: {{ test.completed_at }}</h4>
        {% for c in choices %}
            <div class="d-flex w-100 align-items-center">
                <div class="col-auto flex-shrink-1 flex-grow-1">
                    <h5 class="">{{ forloop.counter }}. {{c.question.description}}</h5>
                </div>
            </div>
            {% for answer in c.question.answer_set.all %}
                <div class="form-check mx-4 d-flex align-items-center">
                    <input class="form-check-input"
                        disabled 
                        type="radio" 
                        name="question_{{ c.question.id }}" 
                        value="{{ answer.id }}"
                        {% if c.answer.id == answer.id %} checked {% endif %}
                    >
                    <label class="{% if c.answer.id == answer.id %} {% if answer.is_correct %} text-success {% else %} text-danger {% endif %} {% endif %} form-check-label ml-3" 
                        for="{{ answer.id }}">
                        {{answer.content}}
                    </label>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}

exammanagement/main/templates/main/test_results.html
{% extends "base_generic.html" %}
{% load i18n %}
{% load keyvalue_action %}

{% block content %}
    <div class="p-4 shadow-4 rounded-3 my-4 exam-bg">
        <h2 class="text-center">{% trans "Chapter" %}: {{ test.chapter.name }} - {{ test.chapter.subject.name }}</h2>
        <h2 class="{% if test.total_score >= test.chapter.min_correct_ans %} text-success {% else %} text-danger {% endif %} text-center">
            {% trans "Total score" %}: {{ test.total_score }} / {{ test.choice_set.all.count }}
        </h2>
        <h4 class="text-secondary fs-6">{% trans "Created at" %}: {{ test.created_at }}</h4>
        <h4 class="text-secondary fs-6">{% trans "Completed at" %}: {{ test.completed_at }}</h4>
        {% for c in choices %}
            <div class="d-flex w-100 align-items-center">
                <div class="col-auto flex-shrink-1 flex-grow-1">
                    <h5 class="">{{ forloop.counter }}. {{c.question.description}}</h5>
                </div>
            </div>
            {% for answer in c.question.answer_set.all %}
                <div class="form-check mx-4 d-flex align-items-center">
                    <input class="form-check-input"
                        disabled
                        type="radio"
                        name="question_{{ c.question.id }}"
                        value="{{ answer.id }}"
                        {% if c.answer.id == answer.id %} checked {% endif %}
                    >
                    <label class="{% if c.answer.id == answer.id %} {% if answer.is_correct %} text-success {% else %} text-danger {% endif %} {% endif %} form-check-label ml-3"
                        for="{{ answer.id }}">
                        {{answer.content}}
                    </label>
                </div>
            {% endfor %}
        {% endfor %}
    </div>
{% endblock %}